### ISSUE TITLE
dropzone

### ISSUE THREAD

**Issue by glensc** [RobLoach/component-installer#75]
so, i tried to use [enyo/dropzone](https://packagist.org/packages/enyo/dropzone), composer downloaded it (v4.0.1), but component-installer did not copy components, even the project has [component.json](https://github.com/enyo/dropzone/blob/master/component.json) file. project has [composer.json](https://github.com/enyo/dropzone/blob/master/composer.json) too, otherwise it wouldn't be found from packagist

so component-installer does not support detached `component.json` file? need to still put everything inside `composer.json`?

**Comment by RobLoach** [comment]
Needs to be a `type` of `component`: https://github.com/enyo/dropzone/pull/857

**Comment by glensc** [comment]
thanks! i was guessing that could be the reason.
