### ISSUE TITLE
not installing component

### ISSUE THREAD

**Issue by glensc** [RobLoach/component-installer#95]
so, i took [existing package](https://github.com/rmm5t/jquery-timeago/tree/v1.4.3) which has [bower.json](https://github.com/rmm5t/jquery-timeago/blob/v1.4.3/bower.json) and [package.json](https://github.com/rmm5t/jquery-timeago/blob/v1.4.3/package.json) (not sure which one component-installer uses), and [added](https://github.com/glensc/jquery-timeago/commit/43c1749a909862d473b11c223776088ea749f3d3) `composer.json` with `type: component` and `require: component-installer`

however, it does not install it's files. not sure what i do wrong here?

`composer.json`:
```json
{
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/glensc/jquery-timeago"
		}
	],
	"minimum-stability": "dev",
	"prefer-stable": true,
	"require-dev": {
		"rmm5t/jquery-timeago": "*"
	}
}
```

```
$ composer install 
Loading composer repositories with package information
Installing dependencies (including require-dev)                             
  - Installing symfony/process (v2.7.7)
    Loading from cache

  - Installing kriswallsmith/assetic (v1.3.2)
    Loading from cache

  - Installing robloach/component-installer (0.2.3)
    Loading from cache

  - Installing rmm5t/jquery-timeago (dev-composer 43c1749)
    Loading from cache

kriswallsmith/assetic suggests installing twig/twig (Assetic provides the integration with the Twig templating engine)
kriswallsmith/assetic suggests installing leafo/lessphp (Assetic provides the integration with the lessphp LESS compiler)
kriswallsmith/assetic suggests installing leafo/scssphp (Assetic provides the integration with the scssphp SCSS compiler)
kriswallsmith/assetic suggests installing ptachoire/cssembed (Assetic provides the integration with phpcssembed to embed data uris)
kriswallsmith/assetic suggests installing leafo/scssphp-compass (Assetic provides the integration with the SCSS compass plugin)
kriswallsmith/assetic suggests installing patchwork/jsqueeze (Assetic provides the integration with the JSqueeze JavaScript compressor)
Writing lock file
Generating autoload files
Compiling component files

$ ls -l components/
total 164K
-rw-rw-r-- 1 glen glen 80K nov   28 14:22 require-built.js
-rw-rw-r-- 1 glen glen 284 nov   28 14:22 require.config.js
-rw-rw-r-- 1 glen glen   0 nov   28 14:22 require.css
-rw-rw-r-- 1 glen glen 80K nov   28 14:22 require.js

$ composer --version
Composer version 1.0.0-alpha10 2015-09-18 14:49:38
```

**Comment by RobLoach** [comment]
You'll need the component files defined in https://github.com/glensc/jquery-timeago/blob/composer/composer.json .

https://github.com/RobLoach/component-installer#creating-a-component

**Comment by glensc** [comment]
didn't it support just reading `bower.json` or `package.json` if they are present in repository?

**Comment by RobLoach** [comment]
@glensc https://packagist.org/packages/fxp/composer-asset-plugin looks like a good one to use bower.json/package.json directly. Let me know what you find!

**Comment by glensc** [comment]
@RobLoach i had feeling that this `component-installer` can also read `bower.json` and `package.json`, seems the answer is no?

and yes, i'm aware of `fxp/composer-asset-plugin`, it's been in my TODO list for a while, to try to use it instead of `component-installer`.

**Comment by RobLoach** [comment]
Correct, `component-installer` does front-end assets in a Composer-way, implementing its own spec. Borrowing from npm or bower would be neat, but I have just used npm or bower when using those files.

As for your implementation, `component-installer` should be part of the root package, not the component itself:

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/glensc/jquery-timeago"
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require-dev": {
        "rmm5t/jquery-timeago": "*",
        "robloach/component-installer": "*"
    }
}
```
